//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BufferedDiffusion.rc
//
#define IDMYOK                          3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_BUFFERTYPE                  129
#define IDD_DIAGIO                      130
#define IDD_DIAGPARAMS                  131
#define IDD_REDRAWDIAG                  132
#define IDD_DIAG_SIMUL_SERIES           135
#define IDR_MENU_EDITCTRL               136
#define IDR_MENU_POP2                   137
#define IDC_DT                          1000
#define IDC_R0                          1001
#define IDC_RMAX                        1002
#define IDC_FIXDR                       1003
#define IDC_FIXM                        1004
#define IDC_DR                          1005
#define IDC_NSLICES                     1006
#define IDC_ALPHA                       1007
#define IDC_BETA                        1008
#define IDC_KD                          1009
#define IDC_CALCALPHA                   1010
#define IDC_CALCBETA                    1011
#define IDC_CALCKD                      1012
#define IDC_DH                          1013
#define IDC_DB                          1014
#define IDC_NITER                       1015
#define IDC_NUPDATE                     1016
#define IDC_PHBULK                      1017
#define IDC_TOTALBUFFER                 1018
#define IDC_IH                          1019
#define IDC_AUTOCALCBUFFERCAPAC         1020
#define IDC_NUMBER                      1021
#define IDC_SIMPLEWAGNERKEIZER          1021
#define IDC_STRING                      1022
#define IDC_WRITEFILES                  1022
#define IDC_OUTFILENAMES                1023
#define IDC_CHANGEFILENAME              1024
#define IDC_CONSTANTCURRENT             1025
#define IDC_TRAIN                       1026
#define IDC_TIMECURRENTON               1027
#define IDC_TIMECURRENTOFF              1028
#define IDC_NPULSESTRAIN                1029
#define IDC_RENORMALIZE                 1030
#define IDC_DT2                         1031
#define IDC_FACTDR                      1032
#define IDC_DT3                         1033
#define IDC_MAXDR                       1034
#define IDC_NROOTS                      1035
#define IDC_USEWAGNERKEIZER             1036
#define IDC_EXTERNALLYSUPPLEIDBUFFERCAPAC 1037
#define IDC_USE_FLUX_CORRECTION         1038
#define IDC_RANGEPH                     1039
#define IDC_FACTORCORRECTION            1040
#define IDC_INTERNALBUFFERCAPAC         1041
#define IDC_CHECK_INCLUDE_FIXED_SURFACE_BUFFER 1042
#define IDC_KD_FIXED_SURFACEBUFFER      1043
#define IDC_REDRAW_INDEX                1043
#define IDC_AMOUNT_FIXED_SURFACEBUFFER  1044
#define IDC_RADIO_GRAY                  1044
#define IDC_AMOUNT_FIXED_THICKNESSFIXEDSURFACE 1045
#define IDC_RADIO_BLACK                 1045
#define IDC_RADIO_RED                   1046
#define IDC_READFILE                    1046
#define IDC_RADIO_GREEN                 1047
#define IDC_EDIT_TOTALTIME              1047
#define IDC_NSECONDSOUT                 1047
#define IDC_RADIO_YELLOW                1048
#define IDC_EDIT_NUMBERCURVES           1048
#define IDC_USE_PREDICTORIN_WAGNERKEIZER 1048
#define IDC_RADIO_BLUE                  1049
#define IDC_EDIT_INTERMEDIATETIME       1049
#define IDC_RADIO_ORANGE                1050
#define IDC_RADIO_PINK                  1051
#define IDC_RADIO_BROWN                 1052
#define IDC_RADIO_LIGHTBLUE             1053
#define IDC_NSIMUL                      1054
#define IDC_USE_TWO_TIMES_POINTS        1055
#define IDC_SHOWREF                     1056
#define IDC_REFINDEX                    1057
#define ID_TEST_TEST                    32771
#define ID_EDIT_PARAMETERS              32772
#define ID_GO_GO                        32773
#define ID_GO_LINEARIZED                32774
#define ID_GO_CLEARWINDIOW              32775
#define ID_GO_SECONDLINEARIZED          32776
#define ID_GO_REDRAWOLDSIMULATION       32777
#define ID_GO_SERIESOFSIMULATIONS       32778
#define ID_MENU_COPY                    32779
#define ID_MENU_PASTE                   32780
#define ID_MENU_CUT                     32781
#define ID_EDITCTRO_COPY                32782
#define ID_EDITCTRO_PASTE               32783
#define ID_EDITCTRO_CUT                 32784
#define ID_SELECT_ALL_EDIT_CTRL         32785
#define ID_EDITCTRLL_SELECTALL          32786
#define ID_EDITCTRLL_COPY               32787
#define ID_EDITCTRLL_CUT                32788
#define ID_EDITCTRLL_PASTE              32789
#define ID_STOP_STOPSERIESSIMULATION    32790
#define ID_FILE_SAVESIMULATIONSERIESONFILE 32791
#define ID_FILE_LOADSIMULATIONSERIESFROMFILE 32792
#define ID_STOP_SLOWALMOSTPAUSESIMULATION 32793
#define ID_STOP_RESTART                 32794
#define ID_STOP_SAVEENERGY              32795
#define ID_STOP_CHANGENOOFSECONDSOUT    32796
#define ID_GO_CONTINUESERIESSIMULATION  32797
#define ID_FILE_READDRDTTABLE           32798
#define ID_FILE_WRITEDRDTTABLE          32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
